# Generated by Django 5.0.4 on 2025-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_auto_20210410_1253"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "前台用户", "verbose_name_plural": "前台用户"},
        ),
        migrations.AddField(
            model_name="comment",
            name="sentiment_label",
            field=models.CharField(
                choices=[("正面", "正面"), ("负面", "负面"), ("中性", "中性")],
                default="中性",
                max_length=10,
                verbose_name="情感标签",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="sentiment_score",
            field=models.FloatField(default=0.5, verbose_name="情感分数"),
        ),
    ]
